SAP/ui5-builder

lib/processors/bundlers/moduleBundler.js
lib/tasks/bundlers/generateComponentPreload.js
lib/types/application/ApplicationBuilder.js

If no component preload configuration is given, use the application namespace. This broke with #6

[FIX] Restore default component preload

---

lib/tasks/createDebugFiles.js
lib/types/application/ApplicationBuilder.js
lib/types/library/LibraryBuilder.js
test/expected/build/application.g/dest/Component-preload.js
test/expected/build/application.g/dest/subcomponentA/Component-preload.js
test/expected/build/application.g/dest/subcomponentB/Component-preload.js
test/lib/tasks/createDebugFiles.js

Temporary fix preventing '*-dbg' files from being included in preload
bundles.
Resolves #12 for the time being

[FIX] Do not bundle debug files

---

CHANGELOG.md

Generation went wrong during automated release due to shallow repository clone

[INTERNAL] Fix Changelog

---

lib/lbt/bundle/Builder.js

- To judge whether a module should be decorated or not depends on
the currently being used bundle format. Therefore the target
bundle format should be used instead of checking whether the
global module is inside the resolved modules

[FIX] Use the target bundle format to decide decoration

---

lib/lbt/analyzer/ComponentAnalyzer.js
lib/lbt/analyzer/FioriElementsAnalyzer.js
lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/analyzer/SmartTemplateAnalyzer.js
lib/lbt/analyzer/XMLCompositeAnalyzer.js
lib/lbt/analyzer/XMLTemplateAnalyzer.js
lib/lbt/bundle/AutoSplitter.js
lib/lbt/bundle/Builder.js
lib/lbt/bundle/Resolver.js
lib/lbt/graph/dependencyGraph.js
lib/lbt/graph/dominatorTree.js
lib/lbt/graph/topologicalSort.js
lib/lbt/resources/ResourceFilterList.js
lib/lbt/resources/ResourcePool.js
lib/lbt/utils/ModuleName.js

- all loggers in the lib/lbt modules now use the same hierarchical
naming scheme as the other modules
- component analyzers no longer fail but return silently when there's
no manifest.json (often occurs in test data)
- more log outputs of the JSModuleAnalyzer now have been classified as
'verbose' to reduce the noise during build
- usages of the Java method 'String.format' that had been missed
during migration have been fixed

Minor improvements around logging and error reporting (in lib/lbt package)

---

lib/processors/uglifier.js

Documentation of uglify-es suggests that `compress:false` already achieves
a very good code size reduction at a much higher speed, see
https://github.com/mishoo/UglifyJS2/tree/harmony#uglify-fast-minify-mode

[FIX] reduce build time at the price of a slightly increased code size

---

lib/types/library/LibraryBuilder.js

the current implementation builds multiple bundles in parallel.
If there's dependency between the bundles, it can't be resolved
correctly. The bundles need to built with the same order as they
are specified in the bundle definition.

[FIX] Bundles should be built one after another

---

lib/lbt/analyzer/ComponentAnalyzer.js
test/lib/lbt/analyzer/ComponentAnalyzer.js

> iterate over routes using a for loop instead of .forEach so we can iterate over objects as well
I figured I might as well create a PR for this issue. afaik this should be the "cleanest" solution for this problem the inner body does not care about the routes name anyway. 
It hurts me a little bit to remove functional syntax and the fat arrow, but I guess its for the greater good ;)
An alternative would be to use `Object.values(routing.routes).forEach` but that would give no access to the route name at all. With the for loop theres still the `key` if one needs the name. 
Additionally I guess this is faster than Object.values.

Fix #30 by using a for loop instead of .forEach

---

lib/processors/debugFileCreator.js
lib/tasks/createDebugFiles.js
test/lib/tasks/createDebugFiles.js

- The `debugFileCreator` processor checks whether the debug file path
is used and only writes the content to the path when it's not
used yet.
- The debug file path can be used, for example, by the `createBundle`
task which may create a specific bundle for the debug version of
another bundle. In this case, the `debugFileCreator` shouldn't
overwrite the created debug bundle.

[INTERNAL] Task createDebugFiles checks path before writes

---

lib/lbt/analyzer/JSModuleAnalyzer.js
test/fixtures/lbt/modules/es6-syntax.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js

The JSModuleAnalyzer internally uses some metadata describing for each
type of ESTree node what properties represent conditionally executed
code branches and what properties represent unconditionally executed
branches. The metadata is used while visiting an AST to classify
dependencies as 'static' or 'conditional'.
During the migration of the analyzer from Java to JavaScript, metadata
was only maintained for a rudimentary set of nodes (basically ES5) and all
other nodes have been marked as 'toBeDone'.
This change closes this gap and maintains metadata for all ES6 node
types; only the types planned for ES7 are kept as 'toBeDone'

[INTERNAL] JSModuleAnalyzer: update language metadata

---

lib/lbt/analyzer/ComponentAnalyzer.js
test/lib/lbt/analyzer/ComponentAnalyzer.js

- accept routes with multiple targets
- merge target-local configuration with main router configuration

[FIX] Close gaps in routing support of ComponentAnalyzer

---

.travis.yml
README.md
greenkeeper.json
package.json

And update `package-lock.json` which got weird with 000a6fee49555cb266a1c575cde719e1091d1066 (EDIT: already done with #48, got removed from this commit)

[INTERNAL] Remove greenkeeper

---

lib/lbt/bundle/Builder.js
package-lock.json
package.json

When using the bundle option usePredefineCalls modules using ES6
features such as arrow functions, classes, ... are not supported
and the bundler will break as the mozilla-ast of uglify-es is not
ES6 ready.

[FEATURE] BundleBuilder: support modules using ES6 with usePredefineCalls

---

lib/processors/versionInfoGenerator.js

Currently the "gav" property isn't filled with any value, so it should
not be added at all, as this currently causes issues when parsing the
value at runtime (e.g. within the UI5 Demokit).
This solves that issue but the "gav" property should anyway be discussed
again.

[FIX] processors/versionInfoGenerator: Remove "gav" property

---

index.js
lib/builder/builder.js
lib/tasks/taskRepository.js
lib/types/AbstractBuilder.js
lib/types/application/ApplicationBuilder.js
lib/types/library/LibraryBuilder.js
lib/types/module/ModuleBuilder.js

As per RFC0004: https://github.com/SAP/ui5-tooling/pull/54

[FEATURE] Builder: Add handling for custom task configurations

---

lib/tasks/bundlers/generateStandaloneAppBundle.js
test/expected/build/application.b/standalone/resources/sap-ui-custom-dbg.js
test/expected/build/application.b/standalone/resources/sap-ui-custom.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js

[FIX] Generate sap-ui-custom-dbg.js for self-contained build

---

lib/lbt/analyzer/SmartTemplateAnalyzer.js
test/lib/lbt/analyzer/SmartTemplateAnalyzer.js

The "pages" property can be either an array or an object.

[FIX] SmartTemplateAnalyzer: Detect dependencies from "pages" object

---

lib/builder/builder.js
package-lock.json
package.json
test/expected/build/application.g/excludes/manifest.json
test/expected/build/application.g/excludes/subcomponentA/manifest.json
test/lib/builder/builder.js
test/lib/tasks/bundlers/generateManifestBundle.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js

Depends on https://github.com/SAP/ui5-fs/pull/140
Partially resolves https://github.com/SAP/ui5-tooling/issues/124
Documentation: https://github.com/SAP/ui5-project/pull/180

[FEATURE] Builder: Add excludes option

---

lib/tasks/jsdoc/generateJsdoc.js
test/lib/tasks/jsdoc/generateJsdoc.js

The targetPath is only used for FS operations. Therefore ist should be
joined natively.

[INTERNAL] generateJsdoc: Use native path.join

---

lib/processors/bundlers/manifestBundler.js
lib/tasks/bundlers/generateManifestBundle.js
lib/types/library/LibraryBuilder.js
test/lib/tasks/bundlers/generateManifestBundle.js

manifestBundler can only include resources from paths that are based on the projects namespace (see regex in manifestBundler ZIP creation).
For other paths the bundling fails because yazl can't add absolute paths.
Also, only resources located in the projects "/resources" should be relevant for manifest bundling.
The latter resovles https://github.com/UI5Lab/UI5Lab-library-simple/issues/11 where with UI5 CLI v1.5.1 the only problem left is, that generateManifestBundle tries to bundle manifest.json resources found in the libraries /test-resources.

[FIX] generateManifestBundle: Only glob files from project namespace

---

lib/lbt/bundle/AutoSplitter.js
lib/lbt/bundle/Builder.js
test/expected/build/sap.ui.core/preload/resources/sap/ui/core/some.js
test/fixtures/sap.ui.core/main/src/sap/ui/core/some.js

Fixes https://github.com/SAP/ui5-builder/issues/257 .

Bundle builder now uses same regexp for copyrights as uglifier task

---

package.json

Exclude eslint config file since it is not treated as source code which
should be covered by a test.

[INTERNAL] coverage: exclude .eslintrc.js

---

lib/lbt/analyzer/JSModuleAnalyzer.js
package-lock.json
package.json

Fixes https://github.com/SAP/ui5-builder/issues/309

[FIX] Adapt to recent extension of estraverse's set of node types

---

jsdoc.json
lib/lbt/analyzer/XMLTemplateAnalyzer.js
lib/lbt/utils/JSTokenizer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/utils/JSTokenizer.js

Starting with UI5 1.69, a core:require attribute can be used in XML
views/fragments to require modules/controls to be used within the XML
context.
https://github.com/SAP/openui5/commit/2dab48e8c3604099f7d2bd56741f5635d3357639
This change supports detecting those modules to be included in bundles.

[FEATURE] XMLTemplateAnalyzer: Support core:require

---

lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js

When processing XML tags with no attributes, getAttributeNS throws Errors like this:
```
(node:9995) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
at Function.values (<anonymous>)
at getAttributeNS (/home/i035043/src/portal-ui/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/XMLTemplateAnalyzer.js:59:22)
at XMLTemplateAnalyzer._analyzeCoreRequire (/home/i035043/src/portal-ui/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/XMLTemplateAnalyzer.js:306:23)
at XMLTemplateAnalyzer._analyzeNode (/home/i035043/src/portal-ui/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/XMLTemplateAnalyzer.js:226:10)
at node.$$.forEach (/home/i035043/src/portal-ui/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/ana …
```

[FIX] Fix errors thrown from template analyzer 

---

lib/processors/manifestCreator.js
test/expected/build/library.h/dest/resources/library/h/components/Component-preload.js
test/expected/build/library.h/dest/resources/library/h/components/TodoComponent.js
test/fixtures/library.h/main/src/library/h/components/TodoComponent.js

In the past files called *Component.js where also considered as
Components during manifest creation.

[FIX] manifestCreator: Only consider component files called Component.js

---

lib/lbt/utils/ModuleName.js
lib/processors/debugFileCreator.js
test/lib/lbt/utils/ModuleName.js
test/lib/tasks/createDebugFiles.js

UI5 runtime knows JavaScript file types controller, designtime, fragment, support and view.
TODO: support files should not be uglified (to keep the rules source code readable). It has to be decided whether this is realized by configuration or whether it should be hard coded in the task / processor or (library) type. Nevertheless, the tooling should know that type anyhow to be able to handle it correctly.
Fixes #336

[INTERNAL] Align set of known file types with runtime

---

lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/bundle/Resolver.js
lib/lbt/resources/ResourcePool.js
lib/tasks/bundlers/generateLibraryPreload.js
test/expected/build/sap.ui.core/preload/resources/sap/ui/core/library-preload.js
test/lib/lbt/bundle/Resolver.js
test/lib/lbt/resources/LibraryFileAnalyzer.js
test/lib/lbt/resources/ResourcePool.js

Fixes https://github.com/SAP/ui5-builder/issues/338

[FIX] Bundling: merge dependency analysis results with raw module infos

---

package-lock.json
package.json

Re-open version range in package.json to patches like grunt-jsdoc is
doing:
https://github.com/krampstudio/grunt-jsdoc/blob/7b4c6eb9db6ae207b18f1fdf37bc71d8c98c76da/package.json#L44
Minor updates tend to break the UI5 JSDoc plugin.

[INTERNAL] Update JSDoc to 3.6.3

---

package.json

Follow-up of https://github.com/SAP/ui5-builder/pull/356

[INTERNAL] jsdoc: Adopt version range to micro releases

---

lib/tasks/buildThemes.js
test/lib/tasks/buildThemes.integration.js
test/lib/tasks/buildThemes.js

[FEATURE] buildThemes: Add "compress" option

---

lib/types/AbstractBuilder.js
test/lib/types/AbstractBuilder.js

Types like "module" do not define any standard tasks. Hence custom tasks
can't reference anything in their "beforeTask" and "afterTask"
configuration.
With this change, the first custom task that a project of such type
defines can omit the before- or afterTask configuration and will be
automatically added as the first tasks.
Resolves https://github.com/SAP/ui5-builder/issues/368

[FEATURE] AbstractBuilder: Allow adding custom tasks for types that have no standard tasks

---

lib/lbt/analyzer/JSModuleAnalyzer.js
test/fixtures/lbt/modules/amd_dynamic_require.js
test/fixtures/lbt/modules/amd_dynamic_require_sync.js
test/fixtures/lbt/modules/declare_dynamic_require.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js

So far, dynamic dependencies only had been detected for calls to
jQuery.sap.require. Now, calls to sap.ui.require and sap.ui.requireSync
are also checked.

[FIX] Detect dynamic dependencies also when newer APIs are used

---

lib/lbt/bundle/AutoSplitter.js
lib/lbt/bundle/Builder.js
lib/lbt/bundle/Resolver.js
lib/lbt/resources/ResourceFilterList.js
test/lib/lbt/resources/ResourceFilterList.js

The 'defaultFileTypes' option for bundles was completely ignored. The
list should be used to limit the set of accepted files when an include
or exclude pattern ends with a '*'.

[FIX] Use 'defaultFileTypes' from bundle configuration

---

lib/types/library/LibraryBuilder.js
lib/types/themeLibrary/ThemeLibraryBuilder.js
lib/types/themeLibrary/ThemeLibraryFormatter.js
lib/types/themeLibrary/themeLibraryType.js
lib/types/typeRepository.js
test/fixtures/theme.library.e/package.json
test/fixtures/theme.library.e/src/theme/library/e/my_theme/.theme
test/fixtures/theme.library.e/src/theme/library/e/my_theme/.theming
test/fixtures/theme.library.e/src/theme/library/e/my_theme/library.source.less
test/fixtures/theme.library.e/ui5.yaml
test/lib/types/themeLibrary/ThemeLibraryFormatter.js

Theme libraries do not require as many features as normal libraries.
For example they do not need a namespace. Also many build tasks are
not required.

[FEATURE] Add new theme-library type

---

lib/lbt/analyzer/JSModuleAnalyzer.js

The UI5 core library contains dynamic calls to sap.ui.require.preload.
Those calls should not result into a warning in the build log, as they
are correct and should just be skipped.
This has been introducted with #341.

[FIX] Bundling: Dynamic preload calls should not emit warnings

---

lib/processors/stringReplacer.js
test/lib/processors/stringReplacer.js

The stream encoding needs to be set in order to properly handle
multi-byte utf8 characters that are split between different chunks.
See:
https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding

[FIX] Ensure proper handling of multi-byte characters in streams

---

lib/types/application/ApplicationBuilder.js

To generate the VersionInfo, the used glob pattern should only match .library files within the resource folder. Otherwise it is possible to find additional .library files, e.g. from unit tests.

[FIX] ApplicationBuilder: Fix pattern to glob for .library files

---

lib/builder/BuildContext.js
lib/builder/builder.js
lib/tasks/buildThemes.js
lib/types/library/LibraryBuilder.js
lib/types/themeLibrary/ThemeLibraryBuilder.js
test/lib/builder/builder.js
test/lib/tasks/buildThemes.js

[FEATURE] buildThemes: Add filtering for available themes

---

lib/lbt/resources/Resource.js

Was used since initial commit. Probably overlooked.

[INTERNAL] lbt/Resource: Use graceful-fs instead of native fs

---

lib/types/application/ApplicationFormatter.js
lib/types/library/LibraryFormatter.js
test/lib/types/application/ApplicationFormatter.js
test/lib/types/library/LibraryFormatter.js

BREAKING CHANGE:
UI5 Project must be able to determine the project's namespace,
otherwise an error is thrown.

[BREAKING] Make namespace mandatory for application and library projects

---

lib/types/library/LibraryFormatter.js
test/lib/types/library/LibraryFormatter.js

If a library contains a nested application project or similar, do not
assume that projects manifest.json to be relevant for the library itself
in case it does not feature a manifest.json.
Instead try to identify such situations by checking whether the
.library file and the manifest.json are on the same directory level.
BREAKING CHANGE:
If a library contains both, a manifest.json and .library file, they must
either be located in the same directory or the manifest.json is ignored.
In cases where the manifest.json is located on a higher level or
different directory on the same level than a .library file, an exception
is thrown.

[BREAKING] LibraryFormatter: Ignore manifest.json of nested apps

---

lib/types/application/ApplicationFormatter.js
lib/types/library/LibraryFormatter.js
lib/types/themeLibrary/ThemeLibraryFormatter.js
test/lib/types/application/ApplicationFormatter.js
test/lib/types/library/LibraryFormatter.js

1. Improve wording in case of missing manifest.json configuration
1. If getDotLibrary() rejects before getManifest() rejects or resolves, no
catch handler is available and an unhandled promise rejection is thrown.  
This is solved by refactoring manifest and .ibrary handling into
separate functions. Imho this also simplifies getNamespace()

[INTERNAL] Namespaces: Improve error messages and fix race condition

---

lib/types/library/LibraryFormatter.js

Add exceptional handling for SAP theme libraries which used to be of
type "library" (today they use "theme-library").
To allow use of OpenUI5 theme libraries in versions lower than 1.75 we
must ignore namespace.

[INTERNAL] LibraryFormatter namespace detection: Add exception for SAP theme libraries

---

test/lib/builder/builder.js
test/lib/tasks/bundlers/generateManifestBundle.integration.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.integration.js
test/lib/tasks/generateCachebusterInfo.js
test/lib/types/AbstractBuilder.js
test/lib/types/application/ApplicationFormatter.js
test/lib/types/library/LibraryFormatter.js
test/lib/types/themeLibrary/ThemeLibraryFormatter.js

Flag was added with https://github.com/SAP/ui5-project/pull/287
Tests are not failing. This is just for consistency reasons and to
prevent future issues.

[INTERNAL] Adapt tests to new project._isRoot flag

---

lib/processors/bundlers/manifestBundler.js
test/lib/processors/bundlers/manifestBundler.js

The manifestBundler task can handle i18n objects configured in the manifest.json "sap.app" "i18n" section.
It is able to support strings:
```json
{
"sap.app": {
"i18n": "i18n/i18n.properties"
}
}
```
as well as objects.
```json
{
"sap.app": {
"i18n": {
"bundleUrl": "i18n/i18n.properties",
"supportedLocales": ["en", "de"],
"fallbackLocale": "en"
}
}
}
```
fixes #457

[FIX] manifestBundler: Add support for i18n object configuration

---

lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js

Fixes: https://github.com/SAP/ui5-builder/issues/281

[FIX] XMLTemplateAnalyzer: Handle empty XML view/fragment

---

index.js
jsdoc-plugin.js
jsdoc.json

Lazy-loading breaks the automatic type definition detection from
TypeScript. Therefore we need to manually declare the exported types.

[FIX] Node.js API: TypeScript type definition support

---

lib/lbt/analyzer/SmartTemplateAnalyzer.js
lib/lbt/resources/ResourcePool.js
lib/processors/bundlers/moduleBundler.js
lib/tasks/bundlers/generateComponentPreload.js
test/lib/lbt/analyzer/SmartTemplateAnalyzer.js
test/lib/lbt/resources/ResourcePool.js

In some cases it can be expected that SmartTemplateAnalyzer does not
have access to second-degree dependencies. In such cases, no error
should be thrown. Currently this causes misleading error logs, for
example in case of component preload generation for a Fiori Elements
project where no framework dependencies are available.
Resolves https://github.com/SAP/ui5-builder/issues/404

[FIX] SmartTemplateAnalyzer: Do not throw in case missing dependency is expected

---

package.json

Since the "self-protection" mechanism of our JSModuleAnalyzer (see https://github.com/SAP/ui5-builder/issues/309#issuecomment-521108883) is
highly dependent on the set of possible node types provided by
estraverse, we often saw problems in consuming projects after new
releases of estraverse. With estraverse@5.2.0 this is yet again the
case.
This change forces consumers to use a version of estraverse that is
supported by JSModuleAnalyzer (currently 5.1.0). Version updates will
only happen through pull requests created by dependabot.

[DEPENDENCY] Pin estraverse to v5.1.0

---

lib/lbt/calls/SapUiDefine.js
lib/lbt/utils/ASTUtils.js
test/lib/lbt/calls/SapUiDefine.js
test/lib/lbt/utils/ASTUtils.js

Other existing implementations, like the one in ui5-migration tooling,
had already been fixed in similar ways.

[FIX] SapUiDefine call should not fail when there's no factory function

---

test/lib/builder/builder.js

This should improve test stability and reduce timeouts in Azure on Windows.
Logs showed that mainly test results of the builder.js tests were missing in case a timeout occurred.
Quick benchmark doesn't show significant overall slowdown.
**master (4ca59a7)**
15.277 s
```
hyperfine --warmup 1 --runs 3 --prepare 'rm -rf test/tmp' 'npm run coverage-xunit' 
Benchmark #1: npm run coverage-xunit
Time (mean ± σ):     15.277 s ±  0.498 s    [User: 48.586 s, System: 11.659 s]
Range (min … max):   14.716 s … 15.666 s    3 runs
```
**builder-tests-sequentially (c2e3c9a)**
15.744 s
```
hyperfine --warmup 1 --runs 3 --prepare 'rm -rf test/tmp' 'npm run coverage-xunit'
Benchmark #1: npm run coverage-xunit
Time (mean ± σ):     15.744 s ±  0.129 s    [User: 50.936 s, System: 12.187 s]
Range (min … max): …
```

[INTERNAL] builder: Run tests sequentially

---

lib/lbt/bundle/Builder.js
test/lib/lbt/bundle/Builder.js

When JSON content is parsed for minification, errors are logged using verbose level.
TheJSON content is not relevant, only for minification.

[INTERNAL] bundleBuilder: log verbose for json parse failure

---

lib/processors/manifestCreator.js
test/lib/processors/manifestCreator.js

library /sap/apf has both a Component.js and a .library file.
This can't be solved due to backward compatibility.
Therefore the log level was decreased from error to verbose.

[INTERNAL] manifestCreator: log verbose for apf

---

test/expected/build/library.h/dest-resources-json/resources/library/h/.library
test/expected/build/library.h/dest-resources-json/resources/library/h/manifest.json
test/expected/build/library.h/dest/resources/library/h/.library
test/expected/build/library.h/dest/resources/library/h/manifest.json
test/fixtures/library.h/main/src/library/h/.library
test/lib/lbt/resources/ModuleInfo.js
test/lib/types/library/LibraryBuilder.js
test/lib/types/themeLibrary/ThemeLibraryBuilder.js

Add tests to increase coverage
Fix naming in manifest.json file of library H

[INTERNAL] Add tests

---

lib/lbt/resources/LocatorResourcePool.js
test/lib/lbt/resources/LocatorResourcePool.js

`ignoreMissingModules` parameter is passed along now when creating
a `new LocatorResourcePool`
works in combination with #479 and #481

[INTERNAL] LocatorResourcePool: pass through constructor arguments

---

lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js

If a `core:require` statement in a node contains an expression
e.g. `core:require="{= '{Handler: \'' + ${myActions > handlerModule} + '\'}'}"`
it is checked if the node resides within a `template` node.
If so the error will be logged with `verbose`.

[INTERNAL] XMLTemplateAnalyzer: check expressions in coreRequire

---

lib/lbt/bundle/Builder.js
lib/lbt/resources/LibraryFileAnalyzer.js
lib/lbt/resources/ModuleInfo.js
lib/lbt/resources/ResourcePool.js
test/expected/build/sap.ui.core/preload/resources/sap/ui/core/.library
test/expected/build/sap.ui.core/preload/resources/sap/ui/core/library-preload.js
test/expected/build/sap.ui.core/preload/resources/sap/ui/core/one.js
test/fixtures/sap.ui.core/main/src/sap/ui/core/.library
test/fixtures/sap.ui.core/main/src/sap/ui/core/one.js
test/lib/lbt/bundle/Builder.js
test/lib/lbt/resources/LibraryFileAnalyzer.js
test/lib/lbt/resources/ModuleInfo.js
test/lib/lbt/resources/ResourcePool.js
test/lib/tasks/bundlers/generateLibraryPreload.integration.js

Ensures that `requiresTopLevelScope` option in `raw-module` configuration from `.library` is preferred and used
when creating the library preload.
`Builder.js`: Use correct variable for `ModuleInfo` (exposedGlobals) to
generate the correct globals assignment in `library-preload.js`

[INTERNAL] generateLibraryPreload: set requiresTopLevelScope correctly

---

package.json

Hopefully this will reduce the number of random failures on Windows on
Azure. Presumably they are caused by some sort of timeout within AVA.

[INTERNAL] package.json: Increase test timeout to 2 minutes (xunit only)

---

lib/lbt/bundle/Builder.js
lib/processors/bundlers/moduleBundler.js
lib/tasks/bundlers/generateLibraryPreload.js
test/lib/tasks/bundlers/generateLibraryPreload.integration.js
test/lib/tasks/bundlers/generateLibraryPreload.js

When a bundle would be empty (not contain any modules), it will be skipped.

[FEATURE] Create designtime and support bundles for libraries

---

lib/lbt/bundle/BundleWriter.js
test/lib/lbt/bundle/BundleWriter.js

The ENDS_WITH_NEW_LINE RegExp is quite slow on large strings.
Therefore the "endsWithNewLine" state is computed after every modification
to the "buf" in order to improve performance.
Based on sap.m build in https://github.com/SAP/openui5/commit/0d95920e3ef1f5712d467298e2eee86ec51e2f63
| Command | Mean [s] | Min [s] | Max [s] |
|:---|---:|---:|---:|
| 2a5194346279279a6fb28c7332245e1cc5360d63 (master)<br>`ui5 build --exclude-task="*" --include-task=generateLibraryPreload` | 15.077 ± 0.355 | 14.476 | 15.499 |
| 713acb3677ba31ea9ad88f5a2f97c58f48df72d3 (BundleWriter-perf)<br>`ui5 build --exclude-task="*" --include-task=generateLibraryPreload` | 12.393 ± 0.334 | 11.883 | 12.913 |

[PERF] BundleWriter: Improve performance

---

lib/lbt/analyzer/JSModuleAnalyzer.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js

Fixes: https://github.com/SAP/ui5-builder/issues/544

[FIX] JSModuleAnalyzer: Properly handle jQuery.sap.registerPreloadedModules calls

---

lib/tasks/generateResourcesJson.js

[INTERNAL] JSDoc: Fix syntax error in generateResourcesJson example

---

lib/lbt/resources/ResourceCollector.js
lib/lbt/resources/ResourceInfoList.js
lib/processors/resourceListCreator.js
test/lib/lbt/resources/ResourceCollector.js
test/lib/lbt/resources/ResourceInfoList.js

Stop analyzing debug-resources if they correspond to a non-debug resource.
Only analyze the non-debug resource and  copy any dependency information to the corresponding debug-resource.
While this might not be the best approach given that analyzing the source ("debug") version of a resource might result in finding more dependencies (i.e. those mangled during minification), this change ensures that we generate the same resources.json, independently from the order of debug and non-debug resources supplied to the resourceListCreator processor.
Resolves https://github.com/SAP/ui5-tooling/issues/274

[FIX] generateResourcesJson: Make resources.json generation deterministic

---

lib/types/application/ApplicationFormatter.js
test/lib/types/application/ApplicationFormatter.js

App Variants typically do not have a manifest.json (they only add that [during the build](https://github.com/SAP/ui5-task-adaptation)) but a manifest.appdescr_variant.
During the project namespace detection, in case no manifest.json is present (error ENOENT), we now attempt a fallback to manifest.appdescr_variant (if present).
For more information see:
* https://help.sap.com/viewer/a7b390faab1140c087b8926571e942b7/202009.000/en-US/af47058ad66144579db6a990f3b7b919.html
* https://blogs.sap.com/2020/07/15/adaptation-project-your-one-stop-tool-for-extending-sapui5-applications
JIRA: CPOUI5FOUNDATION-284

[FEATURE] ApplicationFormatter: Implement manifest.appdescr_variant fallback

---

index.js
lib/processors/libraryLessGenerator.js
test/lib/processors/libraryLessGenerator.js

[FEATURE] Add 'libraryLessGenerator' processor

---

lib/processors/manifestCreator.js
test/expected/build/library.d/dest/resources/library/d/manifest.json
test/expected/build/library.h/dest-resources-json/resources/library/h/manifest.json
test/expected/build/library.h/dest-resources-json/resources/library/h/resources.json
test/expected/build/library.h/dest/resources/library/h/manifest.json
test/expected/build/library.i/dest/resources/library/i/manifest.json
test/expected/build/library.k/dest/resources/library/k/manifest-bundle/manifest.json
test/expected/build/library.k/dest/resources/library/k/manifest.json
test/expected/build/library.ø/dest/resources/library/ø/library-preload.js
test/expected/build/library.ø/dest/resources/library/ø/manifest.json
test/lib/processors/manifestCreator.js
test/lib/tasks/generateLibraryManifest.js

With app descriptor v22 (1.21.0) the i18n sections in the manifest can be an object
with:
* bundleUrl
* supportedLocales
This change reads the provided properties files and automatically creates the supportedLocales
array based on this information.
**files:**
- i18n/i18n.properties
- i18n/i18n_de.properties
- i18n/i18n_en.properties
**snippet in manifest.json**
```json
"i18n": {
"bundleUrl": "i18n/i18n.properties",
"supportedLocales": [
"",
"de",
"en"
]
},
```

[FEATURE] manifestCreator: enrich manifest with supportedLocales in i18n (for libraries)

---

lib/processors/libraryLessGenerator.js
test/lib/processors/libraryLessGenerator.js

To be compatible with the previous behavior (Maven), the processor
should not throw an error in case an import can't be handled.
Instead the error is logged and a comment is added to the resulting
library.less file.

[FIX] processors/libraryLessGenerator: Don't throw in case of import errors

---

lib/tasks/generateThemeDesignerResources.js
lib/types/library/LibraryBuilder.js
test/lib/tasks/buildThemes.integration.js
test/lib/tasks/generateThemeDesignerResources.js

Themes are expected to be within a "themes" folder directly below the
library namespace.
Other "themes" folders (e.g. within sub-directories) should be ignored
and not compiled/processed.

[FIX] Theme Build: Only process themes within library namespace

---

lib/processors/jsdoc/lib/createIndexFiles.js
lib/processors/jsdoc/lib/transformApiJson.js
lib/processors/jsdoc/lib/ui5/plugin.js
lib/processors/jsdoc/lib/ui5/template/publish.js

Includes the following changes
- [INTERNAL] Update copyright year to 2021
SAP/openui5@bc6825e48
- [FIX] Corrected regular expression (SAPHosted)
SAP/openui5@319798593
- [FEATURE] Improve documentation for restricted APIs
SAP/openui5@cb855596b
- generated "auto-doc" honors visibility of target class. If target
class is restricted, generated documentation also has visibility
restricted
- for restricted APIs, export the list of allowed consumers to
api.json (property name 'allowedFor')
- fix split of allowed consumers in tag handler for '@ui5-restricted'
(comma is the only valid separator)
- [FEATURE] Added FAQ section in ApiRef
SAP/openui5@8d2d85e69
An extra FAQ section will be displayed in ApiRef whenever
FAQ content is specified.
- [INTERNAL] Change to inclusive term "excluded"/"included" …

[FEATURE] Align JSDoc template & plugin with OpenUI5 1.87.0

---

lib/builder/builder.js
lib/processors/versionInfoGenerator.js
lib/tasks/generateVersionInfo.js
test/lib/processors/versionInfoGenerator.js
test/lib/tasks/generateVersionInfo.js

Enrich task _generateVersionInfo_, such that the created _version-info.json_ file contains new sections in the json structure:
* _manifestHints_: for each library (in each library's json structure)
* _components_: global (top level in the json structure)
The _manifestHints_ section contains the libraries dependencies (fully resolved).
The resolved dependencies are
* lazy
* if parent dependencies are also lazy
* non-lazy
* if lazy is not defined for this dependency and it has no lazy parent
* if there is the same dependency defined lazy but the current one isn't (non-lazy wins on the same level)
sample:
```json
{
"name": "sap.x",
"version": "1.85.0",
"manifestHints": {
"dependencies": {
"libs": {
"sap.m": { },
"sap.ui.core": { },
"sap.ui.layout": { },
"sap.ui.unified": {
"lazy": true
}
}
} …
```

[FEATURE] Versioninfo enrich with manifest infos

---

lib/processors/versionInfoGenerator.js
test/lib/processors/versionInfoGenerator.js

manifestInfo.embeds can be initial and calling map on initial value will not work, thus default to empty array when initial

[FIX] versionInfoGenerator: manifest without embeds #486

---

lib/processors/jsdoc/sdkTransformer.js
test/lib/processors/jsdoc/sdkTransformer.js

This is just a quick fix, compensating for the new positional parameter
introduced with 0cb02acee2b070889146ef9f725cc139691f0ab2.
A more comprehensive fix should migrate the transformApiJson's API to
named parameters and add tests that ensure a working JSDoc build
including the transformation.
Additionally, a later change should also implement proper handling of
the FAQ markup feature, which has been left out for now.

[FIX] JSDoc: adapt sdkTransformer to change in transformApiJson.js

---

lib/tasks/TaskUtil.js
test/lib/tasks/TaskUtil.js

New specVersion does not affect TaskUtil but still needs to be
supported and handled.

[INTERNAL] TaskUtil: Support specVersion 2.3

---

lib/processors/manifestCreator.js

In the future, we expect libraries to always have a manifest.json and not to rely on this task.
An eventual "manifest enhancement" task could update any dynamic information in an already existing manifest.json, thus making benefits from using the manifestCreator obsolete.

[INTERNAL] manifestCreator: If manifest.json already exists, log message as verbose instead of info

---

lib/processors/resourceListCreator.js
lib/tasks/generateResourcesJson.js
test/lib/processors/resourceListCreator.js
test/lib/tasks/generateResourcesJson.js

The XML analysis requires dependency resources to be able to list them
as "required" in the resources.json.

[FIX] generateResourcesJson: Include dependencies of XML resources

---

lib/processors/manifestCreator.js
test/lib/processors/manifestCreator.js

Field `embeds` in created manifest.json file now contains all nested
manifests, independent from the reverse field `embeddedBy` (`embeddedBy` 
points from an embedded manifest to the library's manifest).
Remove unreachable code (in `createSapUI5()` -> `getUI5Version()` function) .
Use `path.dirname` method to get directory name in `findEmbeddedComponents()` function.
Use string for version value in manifest (in `sectionVersion()` function).
e.g. "1.2.3" instead of the semver object's string representation.
It reverts changes which were introduced with #555
Successor of #554

[FIX] manifestCreator: 'embeds' should list all components

---

lib/lbt/bundle/AutoSplitter.js
lib/lbt/bundle/Builder.js
lib/lbt/bundle/Resolver.js
lib/processors/bundlers/moduleBundler.js
lib/tasks/bundlers/generateComponentPreload.js
lib/tasks/bundlers/generateLibraryPreload.js
lib/tasks/bundlers/generateStandaloneAppBundle.js
test/lib/tasks/bundlers/generateComponentPreload.js
test/lib/tasks/bundlers/generateLibraryPreload.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js

Use default if not provided in bundle definition.
In the past neither a default, nor the bundle definition configuration
was used, since the parameter was mistakenly expected on the bundle
options.
Also align the defaults for library- and component-bundles with Maven.
New moduleBundler defaults:  
* `.js`
* `.control.xml`
* `.fragment.html`
* `.fragment.json`
* `.fragment.xml`
* `.view.html`
* `.view.json`
* `.view.xm`
Component-bundles (Component-preload.js and sap-ui-custom.js) additionally include:
* `.properties`
* and via filters:
* `${namespace}/**/manifest.json`
* `${namespace}/changes/flexibility-bundle.json`
* `${namespace}/changes/changes-bundle.json`

[FIX] moduleBundler: Apply defaultFileTypes

---

lib/processors/versionInfoGenerator.js
test/lib/processors/versionInfoGenerator.js
test/lib/tasks/generateVersionInfo.js

`hasOwnPreload` is only `true` if the library has `embeds` field set in manifest
and embedded manifest does not have a backlink (`embeddedBy`) to the library.

[FIX] versionInfoGenerator: fix hasOwnPreload flag

---

lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js

The conditional flag is now properly taken into account when adding
dependencies within tempate:if or template:repeat tags.
The async execution of ResourcePool#findResource caused the
'conditional' flag to be incorrect as it is updated during the sync
traversal of the nodes.
JIRA: CPOUI5FOUNDATION-347

[FIX] XMLTemplateAnalyzer: Properly detect conditional dependencies

---

lib/lbt/bundle/Builder.js
package-lock.json
package.json
test/lib/lbt/bundle/Builder.js

Replace AST-to-code procedure based on escodegen, which apparently removes comments from the bundled source, with some basic string manipulation.
JIRA: CPOUI5FOUNDATION-260

[FIX] lbt/Builder: Preserve comments in bundles

---

lib/lbt/bundle/Builder.js
lib/lbt/bundle/BundleDefinition.js
lib/processors/bundlers/moduleBundler.js
test/lib/lbt/bundle/Builder.js

When a bundle is created, sections can be added that will be written as
sap.ui.loader.config({bundlesUI5:{...}}) information. Each section of
type 'bundleInfo' represents one single bundle. The section name is the
bundle name, the modules in the section are the modules of the bundle.
It is currently not yet possible to reuse existing bundle definitions to
define the content of such a section.

[FEATURE] Support writing 'bundles' config as part of a bundle

---

lib/processors/jsdoc/jsdocGenerator.js
test/expected/build/library.j/dest/test-resources/library/j/designtime/api.json
test/lib/processors/jsdoc/jsdocGenerator.js

The JSDoc processor did not propagate the library name (project name) to the JSDoc configuration. As a consequence, the UI5 template (publish.js) could not properly validate the metadata property 'library' for control and element classes. It reported many false positives ("ERROR: specified library 'foo.bar' for class 'foo.bar.Control' doesn't match containing library 'undefined'").

[FIX] JSDoc: add project name to JSDoc configuration and api.json

---

lib/processors/debugFileCreator.js
test/lib/tasks/createDebugFiles.js

The debugFileCreator added the '-dbg' suffix to the first occurrence
in the path string which could also be a folder name. This change
ensures that the '.js' file extension is at the end of the string.

[FIX] lib/processors/debugFileCreator: Add -dbg suffix only to files

---

lib/processors/jsdoc/jsdocGenerator.js
test/lib/processors/jsdoc/jsdocGenerator.js

Tests have been adopted to check whether the right information is used.
Follow-up of https://github.com/SAP/ui5-builder/pull/609

[FIX] JSDoc: Use namespace to derive uilib name for jsdoc generator

---

lib/lbt/resources/ResourceCollector.js
test/lib/lbt/resources/ResourceCollector.js

Indicator files like "Component.js", "manifest.json" or ".library" should only be matched
if the full basename is matched.
Before this fix, files like "MyComponent.js" were matched which resulted in the unexpected
creation of a resources.json file. The file should only be created for components, libraries
and themes.

[FIX] lbt/resources/ResourceCollector: Ensure proper matching of indicator files

---

lib/processors/jsdoc/lib/ui5/plugin.js

Checks for a copyright notice at the beginning of each file.
The comment doesn't need to be the first comment but it must be placed
before any code starts.
This implements the same check as the internal validation rule
DOCUMENTATION__COPYRIGHT_NOTICE_MISSING.
Adds a jsdoc exclude configuration for sap.ui.model.odata.datajs which
is a legacy redirect file that only exists in the internal core overlay.
It is configured to be excluded from the internal validation, so it also
needs to be excluded from the jsdoc build so that no error is caused.
JIRA: CPOUI5FOUNDATION-329
Cherry picked from https://github.com/SAP/openui5/commit/bcb511074319aca894a026379bd2979627fb69c7

[INTERNAL] JSDoc: Add check for copyright notice

---

lib/processors/jsdoc/lib/ui5/plugin.js

Follow-up of https://github.com/SAP/ui5-builder/pull/617
Cherry picked from https://github.com/SAP/openui5/commit/f79290bfcf8655a7c71b9d0ea51859405226873b

[INTERNAL] JSDoc: Log resource name instead of full file path

---

lib/builder/builder.js
lib/processors/bundlers/manifestBundler.js
lib/tasks/generateCachebusterInfo.js
lib/types/library/LibraryFormatter.js
test/lib/types/library/LibraryFormatter.js

FS paths containing characters which can be interpreted as regular
expression metacharacters may lead to issues during the namespaces
detection of libraries.
Alternatively we could switch to using
https://www.npmjs.com/package/escape-string-regexp which we already use
elsewhere. But I think this case here can be kept simple.
Fixes https://github.com/SAP/ui5-tooling/issues/526

[FIX] LibraryFormatter: Fix handling of paths containing special characters

---

lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/analyzer/analyzeLibraryJS.js
lib/lbt/utils/parseUtils.js
package.json

Use espree.VisitorKeys instead of those provided by estraverse
since the ui5-builder is already using espree.
The visitor-keys list from estraverse and espree are different
and some unnecessary keys got removed from our list.
Espree is using the "eslint-visitor-keys" library which may contain
unexpected keys due to the used version range. Therefore the
visitor-keys are checked against the available syntax.
The visitor-keys were moved to the parseUtils module.

[INTERNAL] Switch visitor-keys usage from estraverse to espree

---

lib/lbt/analyzer/XMLTemplateAnalyzer.js
lib/lbt/resources/ResourcePool.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js

Also properly wait for the asynchronous analyze function to prevent
unhandled promise rejections and possible race conditions.
Change wording of an unrelated error message.
Resolves https://github.com/SAP/ui5-tooling/issues/539

[FIX] XMLTemplateAnalyzer: Include document name for XML parsing errors

---

lib/types/AbstractBuilder.js
test/lib/types/AbstractBuilder.js

[FIX] AbstractBuilder: Multiple custom task executions did not run

---

lib/processors/jsdoc/lib/ui5/template/publish.js

Improve the determination of 'basename' to also support
the "module:Namespace/Entity" notation.
Trim "module:Namespace/Entity" to "Entity"
JIRA: CPOUI5FOUNDATION-386

[INTERNAL] JSDoc generation: improve basename determination

---

lib/processors/manifestCreator.js
test/lib/processors/manifestCreator.js

The regular expression to trim additional whitespace / line-endings
wasn't working correctly. This is probably caused by the migration from
Java where double backslashes are required.
JIRA: CPOUI5FOUNDATION-422

[FIX] manifestCreator: Trim whitespace/new-lines for sap.app/title

---

lib/builder/ProjectBuildContext.js
lib/tasks/TaskUtil.js

Seems like an oversight in https://github.com/SAP/ui5-builder/pull/535.
The tag can already be used and should be documented in the API reference

[INTERNAL] TaskUtil: Document standard tag 'IsBundle'

---

lib/tasks/buildThemes.js
lib/types/library/LibraryBuilder.js
lib/types/themeLibrary/ThemeLibraryBuilder.js
test/lib/tasks/buildThemes.js

Fixes that libraries using a "library.js" file but no ".library"
file can also build theming files.
Fixes: https://github.com/SAP/ui5-tooling/issues/582

[FIX] Enable buildThemes for libraries without .library

---

lib/lbt/bundle/Resolver.js
test/lib/lbt/graph/topologicalSort.js

Unlike the documentation states, topological sorting of modules within
'raw' sections was not enabled by default.
Sorting is based on dependencies only, so enabling it by default should
only solve issues in case dependencies are declared but sort was not
enabled.
If no dependencies are defined, the order will not change.
This could only break use cases where dependencies have been wrongly
declared and a user relies on the current unsorted order.

[FIX] Bundler: Sort raw modules by default

---

lib/tasks/replaceVersion.js
test/lib/tasks/replaceVersion.js

Ensures that the build task "replaceVersion" replaces
the pattern ${project.version} equally to ${version}.
JIRA: CPOUI5FOUNDATION-423

[INTERNAL] Enhance replaceVersion task to handle ${project.version} pattern

---

lib/tasks/buildThemes.js
lib/types/library/LibraryBuilder.js
lib/types/themeLibrary/ThemeLibraryBuilder.js
test/lib/tasks/buildThemes.js

Fixes that libraries using a "library.js" file but no ".library"
file can also build theming files.
Cherry-pick of https://github.com/SAP/ui5-builder/pull/671

[INTERNAL] Enable buildThemes for libraries without .library

---

lib/processors/bundlers/moduleBundler.js
lib/tasks/bundlers/generateBundle.js
test/lib/processors/bundlers/moduleBundler.js

bundleOptions are often omitted. So document them as optional and always
default 'optimize' to true, even if bundleOptions are specified.
This also fixes a bug that appeared if no 'bundleOptions' are defined in the ui5.yaml (e.g. sap.ui.webc.common).

[BREAKING] moduleBundler: Always default to `optimize: true`

---

lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/utils/parseUtils.js
package-lock.json
package.json
test/fixtures/lbt/modules/es6-syntax.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js
test/lib/lbt/utils/parseUtils.js

By upgrading espree to the latest version, ES2021 language features
are now supported.
JIRA: CPOUI5FOUNDATION-363

[FEATURE] Support ES2021 language features

---

lib/lbt/bundle/AutoSplitter.js
test/lib/lbt/bundle/AutoSplitter.js

Sort modules in preload sections alphabetically.
This caused different bundle contents based on the order of modules that
the resolver provides, which is not deterministic.
Remove terser from size estimation as modules are now already optimized
if the 'optimize' bundle option is enabled.
This caused incorrect estimations about the bundle size which resulted
into size differences of the individual parts.

[FIX] Bundler: Ensure reproducibility for bundles with multiple parts

---

lib/types/library/LibraryBuilder.js
lib/types/themeLibrary/ThemeLibraryBuilder.js

[FEATURE] replaceVersion/Copyright: Also process test-resources

---

lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js

The FragmentDefinition node should be skipped, but it may still contain
a core:require definition.
This is in line with the current runtime which also reads the require
and loads the module.

[FIX] XMLTemplateAnalyzer: Analyze core:require of FragmentDefinition

---

lib/lbt/resources/LocatorResource.js
lib/processors/bundlers/moduleBundler.js
lib/processors/minifier.js
lib/tasks/bundlers/generateBundle.js
lib/tasks/bundlers/generateLibraryPreload.js
lib/tasks/bundlers/generateStandaloneAppBundle.js
lib/tasks/bundlers/utils/createModuleNameMapping.js
lib/tasks/minify.js
test/lib/processors/bundlers/moduleBundler.js
test/lib/processors/minifier.js
test/lib/tasks/bundlers/generateBundle.js
test/lib/tasks/bundlers/generateLibraryPreload.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js
test/lib/tasks/minify.js

Follow-up of https://github.com/SAP/ui5-builder/pull/695

[INTERNAL] SourceMaps follow-up

---

lib/types/library/LibraryBuilder.js
test/lib/types/library/LibraryBuilder.js

Task should be executed after generateManifestBundle, to align with
the current documentation and ApplicationBuilder implementation.

[FIX] LibraryBuilder: Align task order of "generateComponentPreload"

---

lib/tasks/generateLibraryManifest.js
lib/types/library/LibraryBuilder.js
test/lib/tasks/generateLibraryManifest.js

They should not be required to generate a manifest.json for a library
project.

[INTERNAL] generateLibraryManifest: Ignore dependency resources

---

lib/lbt/resources/ResourceCollector.js
lib/lbt/resources/ResourceInfoList.js
lib/lbt/resources/ResourcePool.js
test/lib/lbt/resources/ResourceCollector.js
test/lib/lbt/resources/ResourceInfoList.js

The raw-module info within .library is only maintained using the
non-debug name. Therefore, the analysis must use that name when running
with debug bundles.
Furthermore the handling of the "module" property for debug resources
has been changed to only take place within the ResourceCollector.
JIRA: CPOUI5FOUNDATION-480

[FIX] generateResourcesJson: Add raw-module info for debug bundles

---

lib/processors/jsdoc/lib/transformApiJson.js

Allows using the following JSDoc syntax {@link demo:my/module/page/demo.html My Demo}

[INTERNAL] JSDoc generation: enable links with prefix 'demo:'

---

package-lock.json
package.json
test/lib/builder/builder.js

- Ensure latest terser version
(Related to 4789c2079a460447171dbbf4627ae6d0b56f9e6c)
- Mock Date methods to get a stable timestamp result
Note: mocking a processor isn't easily possible as the @ui5/project
builder is using its own @ui5/builder dependency.

[INTERNAL] Fix tests

---

lib/lbt/bundle/Builder.js
lib/lbt/bundle/Resolver.js
lib/tasks/buildThemes.js

This should help analysing issues.
* bundle/Resolver: The list of resolved modules typically gets truncated
by the console.log anyways: "... xx more items". So we should think of
a better way to output something usefull there if needed (maybe the
count of modules?).
* bundle/Builder: We typically find lots of source maps.
* buildThemes: Not sure about this one, but I think it is typically OK
to not find theme libraries, since they might just not be requested.

[INTERNAL] Move some verbose logging to silly level

---

test/lib/builder/builder.js

To cover verbose logging logic and detect issues like https://github.com/SAP/ui5-project/pull/469

[INTERNAL] builder integration test: Enable verbose logging for build manifest test

---

test/lib/tasks/generateVersionInfo.js

Missing options are already covered by unit test of versionInfoGenerator

[INTERNAL] generateVersionInfo: Remove obsolete test

---

lib/lbt/analyzer/FioriElementsAnalyzer.js
lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/analyzer/SmartTemplateAnalyzer.js
lib/lbt/analyzer/XMLCompositeAnalyzer.js
lib/lbt/analyzer/analyzeLibraryJS.js
lib/lbt/bundle/Builder.js
lib/lbt/calls/SapUiDefine.js
lib/lbt/utils/ASTUtils.js
test/fixtures/lbt/modules/declare_dynamic_require_conditional.js
test/fixtures/lbt/modules/declare_require_conditional.js
test/fixtures/lbt/modules/es6-async-module.js
test/fixtures/lbt/modules/es6-syntax-dynamic-dependencies.js
test/fixtures/lbt/modules/es6-syntax.js
test/fixtures/lbt/modules/es6-template-literal-predefine.js
test/fixtures/lbt/modules/es6-template-literal-with-expression.js
test/fixtures/lbt/modules/es6-template-literal.js
test/lib/lbt/analyzer/FioriElementsAnalyzer.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js
test/lib/lbt/analyzer/SmartTemplateAnalyzer.js
test/lib/lbt/analyzer/XMLCompositeAnalyzer.js
test/lib/lbt/analyzer/analyzeLibraryJS.js
test/lib/lbt/bundle/Builder.js
test/lib/lbt/calls/SapUiDefine.js
test/lib/lbt/utils/ASTUtils.js

[FEATURE] builder: Improve support for ES6+ syntax 

---

package-lock.json
package.json

https://github.com/SAP/ui5-builder/pull/800 for the next branch.
Due to the dev-dependency to ui5-project, the escope@3.6.0 is still present in the package-lock.json, but as a **dev** dependency only. This will be resolved after the next release of ui5-project#next

Revert es5-ext downgrade by bumping escope to 4.0.0

---

test/lib/lbt/bundle/Builder.js
test/lib/processors/themeBuilder.js

Node 19 has a new error message for invalid JSON. Instead of
"Unexpected token o in JSON at position 1" it now reads
"Unexpected token 'o', "no json" is not valid JSON"
Theme builder failed due to missing `await` which now showed up due to https://github.com/SAP/ui5-fs/pull/407

[INTERNAL] Fix tests for invalid JSON and themeBuilder

---

lib/processors/jsdoc/lib/transformApiJson.js

Caused by https://github.com/SAP/ui5-builder/pull/793/commits/d48d2ba171f4da0bbed26473e3e7b94fde59bca9
(cherry picked from https://github.com/SAP/openui5/commit/d3bcca92ff86fb3c5d4b2610ada50f7d85af2a51)
(cherry picked from commit 7d0ac119078d4e04afb646df3b9ee16dfff511b2)

[FIX] transformApiJson: Fix regression in UI5 Tooling scenario

---

lib/processors/jsdoc/jsdocGenerator.js
test/lib/processors/jsdoc/jsdocGenerator.js

BREAKING CHANGE:
The `jsdocGenerator` processor and the corresponding `generateJsdoc` task will now throw an error when JSDoc reports an error (exit code != 0). This will also fail the build when running `ui5 build jsdoc`.
JIRA: CPOUI5FOUNDATION-530

[BREAKING] JSDoc: Fail build when jsdoc command failed

---

lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/utils/ASTUtils.js
lib/lbt/utils/parseUtils.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js
test/lib/lbt/utils/parseUtils.js

[FEATURE] Support ES2022 language features

---

lib/tasks/bundlers/generateBundle.js
test/lib/tasks/bundlers/generateBundle.js

Was missed in https://github.com/SAP/ui5-builder/pull/846

[INTERNAL] generateBundle: Replace AbstractReader#filter with resourceFactory#createFilterReader

---

lib/tasks/bundlers/generateStandaloneAppBundle.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js

Another oversight. Follow up of https://github.com/SAP/ui5-builder/pull/850

[INTERNAL] generateStandaloneAppBundle: Replace AbstractReader#filter with resourceFactory#createFilterReader

---

lib/tasks/jsdoc/generateJsdoc.js

Initially the generateJsDoc task use a buildContext parameter to
register a cleanup task.
In the meantime this functionality is available via the taskUtil.

[BREAKING] generateJsDoc: Remove internal 'buildContext' parameter

---

lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/utils/parseUtils.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js

This change solves the issue of having runtime exceptions when new
VisitorKeys are available via minor version updates of espree.
Instead, a unit test is added to ensure all new VisitorKeys are handled
when updating the ecmaVersion.
We only expect to have new Syntax / VisitorKeys once we update the
ecmaVersion in use, so it shouldn't be an issue when we don't
immediately handle them.

[INTERNAL] Adopt consistency check of EnrichedVisitorKeys

---

lib/tasks/taskRepository.js
test/lib/tasks/taskRepository.js

This is to allow ui5-project to use a taskRepository instance as the
only reference to ui5-builder. This especially eases testing, as a
custom instance can be injected in ui5-project ProjectGraph.
* Add a function to get a list of tasks that have been removed in this
version of ui5-builder
* Add a function to get the effective versions of the @ui5/builder
module the taskRepository instance belongs to and the used @ui5/fs

[INTERNAL] taskRepository: Enhance API for better ui5-project integration

---

lib/processors/jsdoc/lib/ui5/template/publish.cjs

- publish.js: do not write 'module' info for borrowed APIs (part 2)
This is a follow-up to SAP/openui5@9d3fccd91) which only handled the
'module' and 'export' properties and only for borrowed methods.
The same logic now applies to the 'resource' property and also to
borrowed properties (fields) and events.
(Cherry picked from SAP/openui5@d6215d715)
- publish.js: write type of @typedefs to api.json
...as "extends" - when the @typedef has properties and is not a type alias
or function prototype
(Cherry picked from SAP/openui5@5c496b23d)
- publish.js: type parser: accept underscores and $ signs
...in type names. Needed in particular for the newly to-be-introduced
sap.ui.base.Object.$ObjectMetadata etc.
Related to https://github.com/SAP/ui5-typescript/issues/338
(Cherry picked from …

Align lib/processors/jsdoc with openui5/lib/jsdoc

---

lib/lbt/analyzer/ComponentAnalyzer.js
lib/lbt/analyzer/FioriElementsAnalyzer.js
lib/lbt/analyzer/JSModuleAnalyzer.js
lib/lbt/analyzer/SmartTemplateAnalyzer.js
lib/lbt/analyzer/XMLCompositeAnalyzer.js
lib/lbt/analyzer/XMLTemplateAnalyzer.js
lib/lbt/bundle/AutoSplitter.js
lib/lbt/bundle/Builder.js
lib/lbt/bundle/Resolver.js
lib/lbt/graph/dependencyGraph.js
lib/lbt/graph/dominatorTree.js
lib/lbt/graph/topologicalSort.js
lib/lbt/resources/LibraryFileAnalyzer.js
lib/lbt/resources/ResourceCollector.js
lib/lbt/resources/ResourceFilterList.js
lib/lbt/resources/ResourcePool.js
lib/processors/manifestCreator.js
lib/processors/resourceListCreator.js
lib/processors/themeBuilder.js
lib/processors/versionInfoGenerator.js
test/lib/lbt/analyzer/JSModuleAnalyzer.js
test/lib/lbt/analyzer/XMLTemplateAnalyzer.js
test/lib/lbt/bundle/Builder.js
test/lib/lbt/graph/topologicalSort.js
test/lib/lbt/resources/ResourceCollector.js
test/lib/processors/manifestCreator.js
test/lib/processors/resourceListCreator.js
test/lib/tasks/generateVersionInfo.js

Use template literals wherever possible. Start log messages with a
capital letter.
This is in prepration for @ui5/logger changes as per
https://github.com/SAP/ui5-logger/pull/353

[INTERNAL] Refactor log-calls

---

lib/processors/libraryLessGenerator.js
test/lib/processors/libraryLessGenerator.js

This partially reverts https://github.com/SAP/ui5-builder/pull/571.
The processor now fails again when an import can't be inlined, as this
will cause issues when processing the library within the
SAP Theme Designer.

[BREAKING] libraryLessGenerator: Throw error when import can't be inlined

---

package-lock.json
package.json
test/lib/lbt/analyzer/XMLCompositeAnalyzer.js
test/lib/tasks/bundlers/generateLibraryPreload.integration.js

https://github.com/SAP/ui5-logger/pull/363 made logger modules more
restrictive.
* XMLCompositeAnalyzer must provide a module name to create a logger
instance
* generateLibraryPreload integration tests need to be executed in
sequence to prevent issues with the stateful BuildLogger
Depends on https://github.com/SAP/ui5-project/pull/537
JIRA: CPOUI5FOUNDATION-603

[INTERNAL] Fix logger-related tests

---

lib/processors/stringReplacer.js
package-lock.json
package.json
test/lib/processors/stringReplacer.js
test/lib/tasks/minify.js

This allows the processor to only modify a resource if necessary (as in,
a replacement has been applied). Currently, in a standard library build,
this processor is for example the only one to modify JSON files.
However, they often do not contain any of the searched placeholders.
https://github.com/SAP/ui5-fs/pull/472 will enable optimizations for
unmodified resources. So we strive for reducing unnecessary resource
modification across the whole tooling.

[INTERNAL] stringReplacer: Replace using string instead of stream

---

azure-pipelines.yml

With node version 19.4.0 issues came up which might be fixed with a future node version.
Therefore downgrading to 19.3.0.

[INTERNAL] node 19 on windows: use 19.3.0

---

lib/lbt/bundle/Resolver.js
test/lib/lbt/bundle/Builder.js

When a section of type 'bundleInfo' is generated as part of a bundle, the order of the modules in each bundle info is not relevant, but should be stable across different runs.
So far, the order of modules was dependent on the module iteration order of the resource pool and could be random due to I/O timing.

[FIX] lbt/Resolver: ensure stable module order in generated bundleInfo

---

lib/lbt/analyzer/analyzeLibraryJS.js
test/lib/lbt/analyzer/analyzeLibraryJS.js

JIRA: CPOUI5FOUNDATION-476
Analyzes library.js files for dependencies that might be able to initialize a UI5 library. Currently possible options now are:
- `sap.ui.getCore().initLibrary()`- already available
- 
```js 
sap.ui.define(['sap/ui/core/Core',], function(Core) {
var thisLib = Core.initLibrary({
...
```
- 
```js 
sap.ui.define(['sap/ui/core/Lib',], function(Library) {
var thisLib = Library.init({
...
```

[INTERNAL] Support imported Core dependency when analyzing library.js

---

azure-pipelines.yml
package.json

This is to workaround for the `FATAL ERROR: v8::FromJust Maybe value is Nothing.` errors we see for some of our Windows and macOS test executions on Azure.
The error is sporadic, but most consistently appears on Windows 2022 (Azure image '20230630.1.0' and Node v18.16.1.
https://github.com/avajs/ava/issues/2947 seems to suggest this is a Node.js issue as reported at https://github.com/nodejs/node/issues/43304
Disabling the use of our own worker threads in minifier.js resolve the issue. Disabling worker threads in AVA resolves it too.
Since we want to test our worker threads, we opted for the latter by setting the AVA option '--no-worker-threads' for all scripts executed in Azure.
All this indicates an issue with using worker threads (or the workerpool package) from within workers.
Also …

[INTERNAL] Azure: Fix flaky tests on some Windows agents, set CI env variable 

---

azure-pipelines.yml

There are issues with the current Node 20.6.0 version.
See: https://github.com/SAP/ui5-project/pull/657

[INTERNAL] Azure Pipelines: Switch back to Node 20.5.x

---

lib/processors/minifier.js
lib/processors/minifierWorker.js
test/lib/processors/minifier.js

Apparently there are known cases where projects execute a UI5 Tooling build on a previous build result. In this case we will minify previously created (and already minified) preload bundles.
The source maps associated with these bundles are index- (or "sectioned") source maps. Some section maps (for example those generated during the bundling) might be lacking the "names" array. Since this is fine for regular source map, I assume this should be fine for index source maps too.
Apparently, Terser fails to parse these source maps as of today. Therefore we will manually add the missing "names" array for the time being.
I proposed an upstream fix here:
https://github.com/jridgewell/trace-mapping/pull/29

[INTERNAL] Minifier: Fix handling of input source maps of bundles

---

lib/tasks/bundlers/utils/createModuleNameMapping.js
test/lib/tasks/bundlers/generateBundle.js
test/lib/tasks/bundlers/generateLibraryPreload.js
test/lib/tasks/bundlers/utils/createModuleNameMapping.js

This leads to issues where non-JS resources tagged as "IsDebugVariant" (like source map resources) where processed since ModuleName#getNonDebugName can only handle .js and .css extensions.

[INTERNAL] Bundler: Ignore non-JS resources when creating module name mapping

---

lib/processors/minifier.js
lib/tasks/buildThemes.js
test/lib/processors/minifier.js
test/lib/tasks/buildThemes.js

fixes: https://github.com/SAP/ui5-tooling/issues/894
JIRA: CPOUI5FOUNDATION-751
depends on: https://github.com/SAP/ui5-project/pull/677
Workerpool needs to wait for all the active tasks to complete before terminating.

[FIX] Handle graceful termination of workerpool for parallel builds

---

lib/processors/jsdoc/lib/ui5/template/publish.cjs

Align `lib/processors/jsdoc/lib/ui5/template/publish.cjs` with [OpenUI5](https://github.com/SAP/openui5/commit/5f1963602e75996b18c6f160262dc864a7d8ae0e)

[INTERNAL] Align jsdoc publish with UI5

---

lib/processors/bundlers/flexChangesBundler.js
lib/tasks/bundlers/generateFlexChangesBundle.js
test/lib/processors/bundlers/flexChangesBundler.js
test/lib/tasks/bundlers/generateFlexChangesBundle.js

- merge existing level zero changes into the flexibility-bundle.json of UI5 adaptation projects

[FEATURE] flexChangesBundler: Merge existing with new flexibility-bundle.json

---

package-lock.json
package.json
test/lib/builder/builder.js
test/lib/tasks/bundlers/generateLibraryPreload.integration.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.integration.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js
test/lib/tasks/generateCachebusterInfo.js
test/utils/fshelper.js

Get rid of `chai`, `chai-fs` and `recursive-dir`. 
`chai-fs` is not compatible with `chai@v5`. Therefore upgrade to latest `chai` is not possible.
`recursive-dir` is no longer required because node supports option `recursive: true` for native `readdir`

[INTERNAL] tests: remove packages 'chai', 'chai-fs' and 'recursive-dir'

---

lib/tasks/bundlers/generateFlexChangesBundle.js
lib/tasks/bundlers/generateStandaloneAppBundle.js
lib/tasks/generateCachebusterInfo.js
lib/tasks/generateThemeDesignerResources.js
lib/tasks/transformBootstrapHtml.js
test/lib/tasks/bundlers/generateStandaloneAppBundle.js
test/lib/tasks/generateThemeDesignerResources.js
test/lib/tasks/transformBootstrapHtml.js

BREAKING CHANGE:
Task API `namespace` option got renamed to `projectNamespace`
JIRA: CPOUI5FOUNDATION-802
Relates to: https://github.com/SAP/ui5-tooling/issues/701

[BREAKING] Task API arguments rename

---

package-lock.json
package.json
test/expected/build/library.j/dest/test-resources/library/j/designtime/api.json

Test were actually not affected by https://github.com/SAP/ui5-builder/commit/834232db1a81f80e26dc2e4fc663ff83fb933922 due to the circular dependency between ui5-builder and ui5-project. The JSDoc process spawned ui5-builder seems to have resolved it's plugin to the ui5-builder dependency of ui5-project, which was the latest released ui5-builder version.

[INTERNAL] JSDoc: Update test fixtures

---

lib/tasks/bundlers/generateFlexChangesBundle.js
test/lib/tasks/bundlers/generateFlexChangesBundle.js

generateFlexChangesBundle understands minUI5Version as string and array
With the upcoming UI5 2.x the manifest may contain a minUI5Version with multiple entries as described in the AppDescriptor schema (internal PR 499). This change enables the generateFlexChangesBundle to understand the new syntax
in addition, the tests for the generateFlexChangesBundle were enhanced to check better their complete functionality - boy scouted!
JIRA: CLOUDIOI-1170
- [✅] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-tooling/blob/main/CONTRIBUTING.md#-contributing-code)
+ Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/main/CONTRIBUTING.md#how-to-contribute) section 
- [✅] [No merge commits](https://github.com/SAP/ui5-tooling/blob/main/docs/Guidelines.md#no-merge …

[FEATURE] generateFlexChangesBundle: Handle minUI5Version as array

---

lib/tasks/bundlers/generateFlexChangesBundle.js
test/lib/tasks/bundlers/generateFlexChangesBundle.js

With the upcoming UI5 2.x the manifest may contain a minUI5Version with
multiple entries as described in the AppDescriptor schema (internal PR
499). This change enables the generateFlexChangesBundle to understand
the new syntax
in addition, the tests for the generateFlexChangesBundle were enhanced
to check better their complete functionality - boy scouted!
JIRA: CLOUDIOI-1170
(cherry picked from commit 45c9b7efc255e1d62dfed82ccf67b61d54dd8627)

[INTERNAL] generateFlexChangesBundle: Handle minUI5Version as array (#1009)

---

lib/tasks/generateVersionInfo.js
test/lib/tasks/generateVersionInfo.js

Ignore any other project types, even if the project contains a .library file.
Currently, projects of type 'module' will return null as their
namespace, which is then incorrectly used as a string in the constructed
glob pattern.
Projects of type 'library' always provide a valid namespace.
Relates to https://github.com/SAP/ui5-server/pull/656

[INTERNAL] generateVersionInfo: Only process dependencies of type 'library'

---

test/lib/processors/minifier.js
test/lib/tasks/buildThemes.js

Replacing deprecated 'new Buffer(string)' with 'Buffer.from(string)'.
Resolves a TypeError being thrown in our tests when executed with
Node 20.15.0 or 22.3.0.
Root cause: https://github.com/nodejs/node/issues/53075

[INTERNAL] Replace deprecated new Buffer() calls

---

lib/processors/jsdoc/lib/ui5/template/publish.cjs

So far, the documentation build only allowed optional methods in interfaces. But UI5 in several places specifies methods on a base class level without implementing them. Subclasses can then implement such a method to get a certain behavior (example: Control#getAccessibilityInfo).
TypeScript (meanwhile?) allows to describe this as optional methods in the base class.
To allow to use this and thereby to better describe those methods in the TypeScript types, the JSDoc template lifts its limitation and writes out the 'optional' marker also for methods in classes.
Note: this is now even possible for static class methods, although this is not used yet in the framework.
Cherry-picked from SAP/openui5@a7ccde144.

[INTERNAL] lib/processors/jsdoc: support optional methods also in classes

---

lib/tasks/generateThemeDesignerResources.js
lib/tasks/utils/dotTheming.js
package.json
test/lib/package-exports.js
test/lib/tasks/generateThemeDesignerResources.js
test/lib/tasks/utils/dotTheming.js

This change respects an sap.ui.core library .theming file from the sources instead of simply overwriting the file.
It allows the configuration to be put into the library and adjusted there instead of having to adjust it in the build task.
The existing logic is kept to support older UI5 versions where the file is not available in the sources.
JIRA: CPOUI5FOUNDATION-862

[FIX] generateThemeDesignerResources: Allow core .theming in sources

---

lib/tasks/generateThemeDesignerResources.js
lib/tasks/utils/dotTheming.js
package.json
test/lib/package-exports.js
test/lib/tasks/generateThemeDesignerResources.js
test/lib/tasks/utils/dotTheming.js

This change respects an sap.ui.core library .theming file from the sources instead of simply overwriting the file.
It allows the configuration to be put into the library and adjusted there instead of having to adjust it in the build task.
The existing logic is kept to support older UI5 versions where the file is not available in the sources.
JIRA: CPOUI5FOUNDATION-862
(cherry picked from commit dda30114461314e81da43bd739e709186744f592)

[INTERNAL] generateThemeDesignerResources: Allow core .theming in sources

---

test/lib/lbt/analyzer/JSModuleAnalyzer.js

The ES2023 support change (via #1034) missed to update the ECMA version
to activate the VisitorKeys consistency test.

[INTERNAL] Fix VisitorKeys consistency test

---

lib/processors/minifier.js
lib/processors/minifierWorker.js
test/lib/tasks/minify.integration.js

As suggested by Vest in https://github.com/SAP/ui5-tooling/issues/890#issuecomment-2580779768, this should make it easier to identify the resource causing an error in the minify task.

[FIX] minify: In case of error, include full resource path in the error messsage

---

lib/processors/manifestEnhancer.js
test/expected/build/application.o/dest/Component-preload.js
test/expected/build/application.o/dest/i18n/i18n_en_US_sapprc.properties
test/expected/build/application.o/dest/i18n/i18n_en_US_saptrc.properties
test/expected/build/application.o/dest/manifest.json
test/fixtures/application.o/webapp/i18n/i18n_en_US_sapprc.properties
test/fixtures/application.o/webapp/i18n/i18n_en_US_saptrc.properties
test/lib/processors/manifestEnhancer.js

This fixes two problems that could have occurred:
A properties file with an invalid locale was still taken into the list of supported locales, which then caused a runtime exception in the ResourceBundle as it validates the input.
Another problem was that properties files could have a valid name according to BCP47, but the file won't be ever requested with that name.
This is due to the fact that the ResourceBundle does use the legacy Java locale format (using underscores instead of dashes) for the request URL.
In both cases, the properties file is now ignored and no entry for the supportedLocales is created.
Only locales that are valid according to the legacy Java locale format are considered.
However, there is one special case: sr_Latn is also requested by the UI5 runtime, although it …

[FIX] manifestEnhancer: Only use valid files for supportedLocales

---

azure-pipelines.yml
test/utils/fshelper.js

Fix use of deprecated node:fs#Dirent.path. Node v24 removed it, however
in older versions the successor "parentPath" is not yet available.
Therefore we need to fallback to Dirent.path if Dirent.parentPath is
undefined.

[INTERNAL] azure-pipelines.yml: add node v24 to test matrix

---

package-lock.json
package.json

Cheerio v1.1.0 upgraded their dependency to "undici" which now requires "node": ">=20.18.1". This is not compatibly with the current Node support in this project.
See: https://github.com/cheeriojs/cheerio/issues/4747

[FIX] Downgrade cheerio to v1.0.0 to resolve Node compatibility issues

---

lib/lbt/bundle/AutoSplitter.js
lib/lbt/bundle/Builder.js
lib/lbt/utils/stringUtils.js
test/lib/lbt/bundle/AutoSplitter.js

Previously, 'bundleInfo' sections were not considered at all when splitting bundles into multiple parts.
Fixes: https://github.com/SAP/ui5-tooling/issues/1068

[FIX] Bundler: Include 'bundleInfo' section in multipart bundles
