SAP/ui5-builder

- README.md
- Add dependency status badges
- Replace npm version badge with a more reliable one (shields.io kept on
showing "invalid")
> [INTERNAL] Add and update badges

- package-lock.json
- package.json
- test/lib/tasks/buildThemes.js
> [INTERNAL] Update to less-openui5@0.5.4 and fix tests

- .chglog/config.yml
- .chglog/release-config.yml
Scope may contain special characters
> [INTERNAL] CHANGELOG: Fix scope detection in commit messages

- lib/types/module/ModuleBuilder.js
- lib/types/module/ModuleFormatter.js
- lib/types/module/moduleType.js
- lib/types/typeRepository.js
Prerequisite for third-party shimming based on https://github.com/SAP/ui5-tooling/pull/5
Depends on https://github.com/SAP/ui5-project/pull/46
Example implementation: https://github.com/RandomByte/openui5-parallax/pull/1/files#diff-f7cafeb3d075b6c5d28c1102cec23f52R14
> [FEATURE] Add module type

- lib/tasks/bundlers/generateLibraryPreload.js
- Missing sap-ui-optimized flag prevented load of preloads
- Missing debug try-catch wrapper prevented use of debug mode
> [FIX] generateLibraryPreload: Fix sap-ui-core.js bootstrap

- lib/lbt/analyzer/XMLTemplateAnalyzer.js
Fixes: #108
A test should be added after #120 has been merged
> [FIX] XMLTemplateAnalyzer: Ignore properties with data binding

- test/fixtures/lbt/modules/es6-syntax.js
- test/lib/lbt/analyzer/XMLTemplateAnalyzer.js
Adds some missing test cases
See: https://github.com/SAP/ui5-builder/issues/108, https://github.com/SAP/ui5-builder/pull/130
See: https://github.com/SAP/ui5-builder/pull/64, https://github.com/SAP/ui5-tooling/issues/69
> Add missing test cases

- lib/lbt/analyzer/JSModuleAnalyzer.js
- lib/lbt/utils/ASTUtils.js
- test/lib/lbt/utils/ASTUtils.js
> [FIX] Include module name in log for duplicate module declaration

- lib/tasks/bundlers/generateLibraryPreload.js
- test/expected/build/sap.ui.core/preload/resources/sap-ui-core-dbg.js
- test/lib/tasks/bundlers/generateLibraryPreload.js
> [FIX] Bundler: Create sap-ui-core-dbg.js

- index.js
- lib/builder/builder.js
- lib/tasks/generateCachebusterInfo.js
- lib/tasks/taskRepository.js
- lib/types/application/ApplicationBuilder.js
- test/expected/build/application.g/cachebuster/Component-dbg.js
- test/expected/build/application.g/cachebuster/Component-preload.js
- test/expected/build/application.g/cachebuster/Component.js
- test/expected/build/application.g/cachebuster/manifest.json
- test/expected/build/application.g/cachebuster/sap-ui-cachebuster-info.json
- test/expected/build/application.g/cachebuster/subcomponentA/Component-dbg.js
- test/expected/build/application.g/cachebuster/subcomponentA/Component.js
- test/expected/build/application.g/cachebuster/subcomponentA/manifest.json
- test/expected/build/application.g/cachebuster/subcomponentB/Component-dbg.js
- test/expected/build/application.g/cachebuster/subcomponentB/Component.js
- test/expected/build/application.g/cachebuster/subcomponentB/manifest.json
- test/lib/builder/builder.js
- test/lib/tasks/generateCachebusterInfo.js
- test/lib/types/application/ApplicationBuilder.js
> [FEATURE] Generate the AppCacheBuster index file for apps

- lib/processors/bundlers/manifestBundler.js
- lib/tasks/bundlers/generateManifestBundle.js
- lib/types/application/ApplicationBuilder.js
- lib/types/library/LibraryBuilder.js
- test/expected/build/application.b/dest/manifest-bundle/embedded/i18n/i18n.properties
- test/expected/build/application.b/dest/manifest-bundle/embedded/i18n/i18n_de.properties
- test/expected/build/application.b/dest/manifest-bundle/embedded/manifest.json
- test/expected/build/application.b/dest/manifest-bundle/i18n/i18n.properties
- test/expected/build/application.b/dest/manifest-bundle/i18n/i18n_de.properties
- test/expected/build/application.b/dest/manifest-bundle/manifest.json
- test/expected/build/library.k/dest/resources/library/k/.library
- test/expected/build/library.k/dest/resources/library/k/library.js
- test/expected/build/library.k/dest/resources/library/k/manifest-bundle/manifest.json
- test/expected/build/library.k/dest/resources/library/k/manifest.json
- test/expected/build/library.k/dest/resources/library/k/messagebundle.properties
- test/expected/build/library.k/dest/resources/library/k/messagebundle_de.properties
- test/expected/build/library.k/dest/resources/library/k/messagebundle_en.properties
- test/fixtures/library.k/package.json
- test/fixtures/library.k/src/library/k/.library
- test/fixtures/library.k/src/library/k/library.js
- test/fixtures/library.k/src/library/k/messagebundle.properties
- test/fixtures/library.k/src/library/k/messagebundle_de.properties
- test/fixtures/library.k/src/library/k/messagebundle_en.properties
- test/fixtures/library.k/ui5.yaml
- test/lib/tasks/bundlers/generateManifestBundle.js
- test/lib/types/application/ApplicationBuilder.js
Fixes: https://github.com/SAP/ui5-builder/issues/144
> [FEATURE] Build the manifest-bundle.zip for applications and libraries

- package-lock.json
- package.json
This resolves an error "Cannot read property 'items' of undefined" when
executing the JSDoc build for the sap.ui.core library.
> [FIX] package.json: Fix JSDoc version to 3.5.5

- lib/builder/BuildContext.js
- lib/builder/builder.js
- lib/tasks/jsdoc/generateJsdoc.js
- lib/types/AbstractBuilder.js
- lib/types/application/applicationType.js
- lib/types/library/LibraryBuilder.js
- lib/types/library/libraryType.js
- package-lock.json
- package.json
- test/lib/builder/builder.js
- test/lib/tasks/jsdoc/generateJsdoc.js
For this a new entity 'BuildContext' has been introduced in the builder.
This might be the foundation for future enhancements of the (Custom-)
Task API.
Resolves SAP/ui5-cli#187
> [FIX] JSDoc: Implement own tmp dir lifecycle

- package-lock.json
- package.json
Only used in azure pipelines environment.
> [INTERNAL] package.json: Make tap-xunit dependency a devDependency

- README.md
Related to https://github.com/SAP/ui5-tooling/pull/160
> [INTERNAL] README: Move documentation to UI5 Tooling repository

- lib/processors/bundlers/moduleBundler.js
- lib/tasks/bundlers/generateBundle.js
Adding JSDoc regarding bundleDefinition and bundleOptions to generateBundle task and moduleBundler processor
> [INTERNAL] Add JSDoc regarding bundleDefinition and bundleOptions

- lib/tasks/bundlers/generateFlexChangesBundle.js
- test/expected/build/application.i/dest/manifest.json
- test/expected/build/application.j/dest/manifest.json
- Ensure existence of sap.ui5 and sap.ui5/dependencies sections
- Format modified manifest.json with tabs
- Modify manifest json once after writing processed resources
- Refactoring
> [INTERNAL] generateFlexChangesBundle: Follow-up adjustments

- lib/lbt/bundle/AutoSplitter.js
- lib/lbt/bundle/Builder.js
- lib/processors/uglifier.js
- package-lock.json
- package.json
See #330. Wrapping functions
passed to `sap.ui.define` in parenthesis might actually impact the
performance of UI5 applications in a negative way.
> [INTERNAL] In-range update of npm dependencies

- lib/types/AbstractBuilder.js
- test/lib/types/AbstractBuilder.js
Resolves https://github.com/SAP/ui5-tooling/issues/153
> [FEATURE] Simple Build Extensibility: Pass project namespace to custom tasks

- package-lock.json
- package.json
> [DEPENDENCY] Bump less-openui5 from 0.6.0 to 0.7.0

- lib/processors/themeBuilder.js
- lib/tasks/buildThemes.js
- package-lock.json
- package.json
- test/lib/processors/themeBuilder.js
- test/lib/tasks/buildThemes.js
> feature: enable css-vars and skeleton build

- lib/types/themeLibrary/ThemeLibraryBuilder.js
> [INTERNAL] ThemeLibraryBuilder: Remove unused tasks

- lib/lbt/utils/escapePropertiesFile.js
- lib/types/application/ApplicationFormatter.js
- lib/types/library/LibraryFormatter.js
- test/fixtures/application.h/ui5.yaml
- test/lib/lbt/utils/escapePropertiesFile.js
- test/lib/types/application/ApplicationFormatter.js
- test/lib/types/library/LibraryFormatter.js
Related:
- https://github.com/SAP/ui5-server/pull/303
- https://github.com/SAP/ui5-project/pull/293
> [INTERNAL] SpecVersion 2+: Default propertiesFileSourceEncoding to UTF-8

- lib/processors/bundlers/moduleBundler.js
There is no code defaulting this parameter to true. @codeworrior sometime we should discuss whether this parameter is still needed at all.
> [INTERNAL] moduleBundler: Fix JSDoc default for declareRawModules parameter

- test/lib/tasks/bundlers/generateComponentPreload.js
> [INTERNAL] generateComponentPreload: Add basic unit test

- lib/processors/resourceListCreator.js
- lib/tasks/generateResourcesJson.js
- test/lib/processors/resourceListCreator.js
- test/lib/tasks/generateResourcesJson.js
> [INTERNAL] resourceListCreator: API round-offs (failOnOrphans=false)

- .github/workflows/codeql-analysis.yml
I used the action's [template](https://github.com/SAP/ui5-builder/new/master?code_scanning_workflow_template=codeql&filename=.github%2Fworkflows%2Fcodeql-analysis.yml) and removed some parts since we only use one language (no need for a matrix) and no build is necessary (therefore no need for `github/codeql-action/autobuild`)
> [INTERNAL] Add CodeQL Action

- lib/processors/bundlers/manifestBundler.js
- test/lib/processors/bundlers/manifestBundler.js
> [FEATURE] manifestBundler: Add support for sap.app/i18n/enhanceWith

- lib/processors/jsdoc/lib/ui5/plugin.js
- lib/processors/jsdoc/lib/ui5/template/publish.js
Cherry picked from https://github.com/SAP/openui5/commit/7102432db
> [INTERNAL] JSDoc: migrate template and plugin implementation to ES6+

- lib/processors/bundlers/moduleBundler.js
- lib/tasks/bundlers/generateComponentPreload.js
- lib/tasks/bundlers/generateLibraryPreload.js
Follow-up of: https://github.com/SAP/ui5-builder/pull/573
> [INTERNAL] Apply UA review from preload-excludes PR

- lib/lbt/resources/ResourceCollector.js
- lib/lbt/resources/ResourcePool.js
- test/expected/build/application.j/dest-resources-json/resources.json
- test/expected/build/library.h/dest-resources-json/resources/library/h/components/resources.json
- test/expected/build/library.h/dest-resources-json/resources/library/h/components/subcomponent1/resources.json
- test/expected/build/library.h/dest-resources-json/resources/library/h/components/subcomponent2/resources.json
- test/expected/build/library.h/dest-resources-json/resources/library/h/components/subcomponent3/resources.json
- test/expected/build/library.h/dest-resources-json/resources/library/h/resources.json
- test/lib/lbt/resources/ResourcePool.js
- test/lib/processors/resourceListCreator.js
> [FIX] resourceListCreator: Include dependencies of subModules

- lib/builder/builder.js
- test/lib/builder/builder-composeTaskList.js
Fixes: https://github.com/SAP/ui5-tooling/issues/510
> [FIX] Emit warning when including/excluding unknown tasks

- lib/tasks/TaskUtil.js
- test/lib/tasks/TaskUtil.js
> [INTERNAL] TaskUtil: Support specVersion 2.4

- lib/tasks/TaskUtil.js
- test/lib/tasks/TaskUtil.js
> [INTERNAL] TaskUtil: Support specVersion 2.5

- lib/lbt/analyzer/JSModuleAnalyzer.js
- lib/lbt/utils/parseUtils.js
- package-lock.json
- package.json
> [INTERNAL] Upgrade espree to v9.3.1

- lib/processors/jsdoc/lib/transformApiJson.js
> [INTERNAL] JSDoc generation: enable links with prefix 'demo:'

- lib/types/AbstractBuilder.js
By using the environment variable `UI5_PERF_TASK=true` the processing time of a task is calculated and written to the log
BLI: CPOUI5FOUNDATION-497
> [INTERNAL] Enable task processing time measurement

- lib/tasks/generateResourcesJson.js
> [INTERNAL] Use new OpenUI5 SDK url

- lib/tasks/TaskUtil.js
- package-lock.json
- package.json
- test/lib/builder/builder.js
- test/lib/tasks/TaskUtil.js
- test/lib/tasks/bundlers/generateLibraryPreload.integration.js
- test/lib/tasks/bundlers/generateManifestBundle.integration.js
- test/lib/tasks/bundlers/generateStandaloneAppBundle.integration.js
- test/lib/tasks/generateCachebusterInfo.js
See https://github.com/SAP/ui5-project/pull/460
> [INTERNAL] Adapt tests to builder changes in @ui5/project

- package-lock.json
- package.json
Cherry-pick of https://github.com/SAP/ui5-builder/pull/798
> [FIX] package.json: Downgrade es5-ext dependency

- lib/lbt/analyzer/ComponentAnalyzer.js
- lib/lbt/analyzer/XMLTemplateAnalyzer.js
- test/lib/lbt/analyzer/ComponentAnalyzer.js
- test/lib/lbt/analyzer/XMLTemplateAnalyzer.js
Fixes: https://github.com/SAP/ui5-tooling/issues/624
> [FIX] ComponentAnalyzer / XMLTemplateAnalyzer detection of views

- lib/lbt/analyzer/ComponentAnalyzer.js
- lib/lbt/analyzer/XMLTemplateAnalyzer.js
- test/lib/lbt/analyzer/ComponentAnalyzer.js
- test/lib/lbt/analyzer/XMLTemplateAnalyzer.js
Cherry-pick of https://github.com/SAP/ui5-builder/pull/808
> [INTERNAL] ComponentAnalyzer / XMLTemplateAnalyzer detection of views

- lib/lbt/utils/escapePropertiesFile.js
- lib/tasks/bundlers/generateLibraryPreload.js
- package-lock.json
- package.json
- test/lib/lbt/utils/escapePropertiesFile.js
- test/lib/tasks/bundlers/generateLibraryPreload.js
See https://github.com/SAP/ui5-project/pull/431
> [INTERNAL] Adapt to new Specification#getSpecVersion implementation

- lib/tasks/bundlers/generateComponentPreload.js
- lib/tasks/bundlers/generateLibraryPreload.js
- test/lib/tasks/bundlers/generateComponentPreload.js
- test/lib/tasks/bundlers/generateLibraryPreload.js
Depends on https://github.com/SAP/ui5-project/pull/514
Relates to https://github.com/SAP/ui5-fs/pull/438
> [INTERNAL] Replace AbstractReader#filter with resourceFactory#createFilterReader

- test/lib/builder/builder.js
See: https://github.com/SAP/ui5-project/pull/542
> [INTERNAL] Prepare tests to work with upcoming @ui5/project changes

- lib/processors/minifier.js
- lib/processors/minifierWorker.js
- lib/tasks/minify.js
- package-lock.json
- package.json
- test/lib/processors/minifier.js
- test/lib/tasks/minify.js
Based on https://github.com/SAP/ui5-builder/pull/700:
* Changed logging to verbose
* Added option 'useWorkers' to processor. Implicit activation through
taskUtil parameter seemed a bit odd. Moved that to the minify task
* Added JSDoc
> [FEATURE] minify task: Use workerpool for terser

- test/lib/builder/builder.js
- test/lib/lbt/resources/LocatorResourcePool.js
- test/lib/processors/bundlers/flexChangesBundler.js
- test/lib/processors/nonAsciiEscaper.js
Related to https://github.com/SAP/ui5-fs/pull/481
> [INTERNAL] Tests: Create all resources with absolute paths

- .github/workflows/dependabot-auto-merge.yml
> [INTERNAL] dependabot auto-merge: update trigger types and conditions

- lib/lbt/analyzer/analyzeLibraryJS.js
- test/lib/lbt/analyzer/analyzeLibraryJS.js
> [FEATURE] Validate apiVersion property in Library.init

- lib/lbt/resources/ResourceFilterList.js
JIRA: CPOUI5FOUNDATION-728
fixes: https://github.com/SAP/ui5-builder/security/code-scanning/2
> [FIX] Incomplete string escaping or encoding

- lib/processors/jsdoc/lib/ui5/template/publish.cjs
JIRA: CPOUI5FOUNDATION-728
fixes: https://github.com/SAP/ui5-builder/security/code-scanning/19
Details: https://codeql.github.com/codeql-query-help/javascript/js-prototype-pollution-utility
> [FIX] Add guard against prototype pollution

- lib/processors/manifestCreator.js
JIRA: CPOUI5FOUNDATION-728
fixes: https://github.com/SAP/ui5-builder/security/code-scanning/20
Details: https://codeql.github.com/codeql-query-help/javascript/js-incomplete-multi-character-sanitization/
> [FIX] Incomplete multi-character sanitization

- .reuse/dep5
- LICENSE.txt
- lib/processors/jsdoc/lib/createIndexFiles.cjs
- lib/processors/jsdoc/lib/transformApiJson.cjs
- lib/processors/jsdoc/lib/ui5/plugin.cjs
- lib/processors/jsdoc/lib/ui5/template/publish.cjs
- [INTERNAL] license: Update copyright year to 2024
- [INTERNAL] lib/processors/jsdoc: Update copyright year to 2024
JIRA: CPOUI5FOUNDATION-617
> [INTERNAL] Update copyright year to 2024

- lib/processors/bundlers/flexChangesBundler.js
- lib/tasks/bundlers/generateFlexChangesBundle.js
- test/lib/processors/bundlers/flexChangesBundler.js
- test/lib/tasks/bundlers/generateFlexChangesBundle.js
Merge any existing level zero changes into the flexibility-bundle.json
of UI5 adaptation projects
Cherry-pick of https://github.com/SAP/ui5-builder/pull/974
> [FIX] flexChangesBundler: Merge existing with new flexibility-bundle.json

- .chglog/release-config.yml
- README.md
- jsdoc.json
- package.json
> [INTERNAL] Setup main branch for UI5 Tooling V4

- lib/processors/minifier.js
JIRA: CPOUI5FOUNDATION-802
https://github.com/jridgewell/trace-mapping/pull/29 got resolved and merged, but Terser still have not updated their dependency
> [INTERNAL] Move TODOs for 5.0 

- lib/processors/jsdoc/lib/transformApiJson.cjs
- lib/processors/jsdoc/lib/ui5/plugin.cjs
- lib/processors/jsdoc/lib/ui5/template/publish.cjs
Cherry picked from SAP/openui5@a6098ae
> [INTERNAL] lib/processors/jsdoc: Introduce 'restricted' visibility and '@type' support

- lib/processors/bundlers/moduleBundler.js
- test/lib/processors/bundlers/moduleBundler.js
> [FEATURE] Apply default values to bunde definitions for standard tasks

- lib/lbt/bundle/Builder.js
- test/lib/lbt/bundle/Builder.js
In case 'targetUi5CoreVersionMajor' can not be determined, set it to 'null'
to hightlight that the value was checked but not set.
> [INTERNAL] lib/lbt/bundle/Builder: Set 'targetUi5CoreVersionMajor' correctly

- .chglog/CHANGELOG.tpl.md
- CHANGELOG.md
> [INTERNAL] .chglog/CHANGELOG.tpl.md: Add missing v3 releases

- .reuse/dep5
- LICENSE.txt
- lib/processors/jsdoc/lib/createIndexFiles.js
- lib/processors/jsdoc/lib/transformApiJson.js
- lib/processors/jsdoc/lib/ui5/plugin.js
- lib/processors/jsdoc/lib/ui5/template/publish.js
- lib/processors/jsdoc/lib/ui5/template/utils/typeParser.js
> [INTERNAL] Update copyright year to 2025

- lib/lbt/bundle/Builder.js
- test/lib/lbt/bundle/Builder.js
> [FIX] Handle legacy-free UI5 versions
